### ISSUE TITLE
i have a question, can you help me ?

### ISSUE THREAD

**Issue by bluesiboy** [jesserwright/ryzentosh#1]
i have a question, can you help me ?

my master board is b450M, cpu is r7 3800x , gpu is rx 580 4G.
mac can success boot , and use it !
but, my GPU meory is fill full,
when this happens, screen is torn and frozen.
and mouse is not moving, he is flashing!!!
flash, you know this is skill by LOL game.

**Comment by bluesiboy** [comment]
![QQ20200319-002942](https://user-images.githubusercontent.com/9855885/76984224-8154d080-6979-11ea-970a-9f4cb75db064.png)
![QQ20200319-003024](https://user-images.githubusercontent.com/9855885/76984241-874ab180-6979-11ea-8d88-b4495e249665.png)
![QQ20200319-003125](https://user-images.githubusercontent.com/9855885/76984246-89147500-6979-11ea-953a-9d5eff4d3293.png)
![QQ20200319-003141](https://user-images.githubusercontent.com/9855885/76984268-8f0a5600-6979-11ea-9c47-fcf83aac5659.png)
![QQ20200319-003206](https://user-images.githubusercontent.com/9855885/76984298-97fb2780-6979-11ea-90f8-a226aa9ec321.png)

**Comment by jesserwright** [comment]
Hey, I'm sorry I cannot help with your specific issue without knowing a lot more about how the kernel is being loaded. I followed this to get my rig running: https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/
